### ISSUE TITLE
QC failing not related to the changes in PR

### ISSUE THREAD

**Issue by anitacaron** [monarch-initiative/monarch-mapping-commons#48]
Can someone please check why is failing the QC not related to the changes in the PR #29. 

https://github.com/monarch-initiative/monarch-mapping-commons/actions/runs/7099943211/job/19331974508

```
INFO:root:Importing linkml:types as /usr/local/lib/python3.10/dist-packages/linkml_runtime/linkml_model/model/schema/types from source /usr/local/lib/python3.10/dist-packages/sssom_schema/schema/sssom_schema.yaml; base_dir=None
/usr/local/lib/python3.10/dist-packages/sssom/parsers.py:204: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("", inplace=True)
Traceback (most recent call last):
  File "/usr/local/bin/sssom", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sssom/cli.py", line 215, in parse
    parse_file(
  File "/usr/local/lib/python3.10/dist-packages/sssom/io.py", line 98, in parse_file
    doc = parse_func(
  File "/usr/local/lib/python3.10/dist-packages/sssom/parsers.py", line 290, in parse_sssom_table
    msdf = from_sssom_dataframe(df, prefix_map=meta_all.prefix_map, meta=meta_all.metadata)
  File "/usr/local/lib/python3.10/dist-packages/sssom/parsers.py", line 485, in from_sssom_dataframe
    mlist.append(_prepare_mapping(Mapping(**mdict)))
  File "<string>", line 47, in __init__
  File "/usr/local/lib/python3.10/dist-packages/sssom_schema/datamodel/sssom_schema.py", line 263, in __post_init__
    self.MissingRequiredField("subject_id")
  File "/usr/local/lib/python3.10/dist-packages/linkml_runtime/utils/yamlutils.py", line 273, in MissingRequiredField
    raise ValueError(f"{field_name} must be supplied")
ValueError: subject_id must be supplied
make[1]: *** [monarch_mapping_commons.Makefile:31: mappings/gene_mappings.sssom.tsv] Error 1
make[1]: Leaving directory '/__w/monarch-mapping-commons/monarch-mapping-commons'
make: *** [Makefile:37: mappings] Error 2
Error: Process completed with exit code 2.
```

**Comment by glass-ships** [comment]
This is a result of the fixes for #46 (PRs https://github.com/monarch-initiative/monarch-mapping-commons/pull/47 and https://github.com/monarch-initiative/monarch-gene-mapping/pull/34)

I only yesterday re-built the gene-mapping file after merging that PR and noticed this issue when I tried to update this repository using that file. Unfortunately I'm not sure why this happened, however @cthoyt just left a couple [comments on the gene mapping PR](https://github.com/monarch-initiative/monarch-gene-mapping/pull/34/files#r1415833331) suggesting some options that may? help to fix this

**Comment by matentzn** [comment]
Lets all use the sssom converter:

https://github.com/monarch-initiative/monarch-gene-mapping/issues/35

which is based on the bioregistry epm which has all the synonyms

**Comment by matentzn** [comment]
Thanks @glass-ships!!
